GRANT CONNECT ON DATABASE opb2025_popovma TO napreti;

GRANT USAGE ON SCHEMA public TO napreti;



GRANT ALL ON ALL TABLES IN SCHEMA public TO napreti;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO napreti;



ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO napreti;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO napreti;


