GRANT CONNECT ON DATABASE opb2025_popovma TO javnost;

GRANT USAGE ON SCHEMA public TO javnost;

GRANT ALL ON ALL TABLES IN SCHEMA public TO javnost;


ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO javnost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO javnost;


SELECT * FROM knjiga;
